language: php

php:
    - "7.4"
    # - hhvm
    # - nightly

env:
    global:
        - XDEBUG_MODE=coverage

# matrix:
#     allow_failures:
#         - php: nightly
#         - php: hhvm

sudo: false

git:
    submodules: false

before_script:
    - make install

script:
    - make test
